mel 데이터 로드

In [4]:
import pandas as pd
import numpy as np

In [7]:
pca=np.load('D:/PCA/0.npy')
pca.shape

(13463, 100)

In [12]:
# plyst_pca=np.array(plyst_pca)

In [13]:
plyst_pca=np.array(plyst_pca)
plyst_pca.shape

(100,)

In [14]:
plyst_pca[0].shape

(81, 100)

PCA 적용된 합쳐진 플레이리스트를 각 플레이리스트로 분할하기

In [11]:
plyst_pca =[]
before = 0
for i in long:
    plyst_pca.append(mel_a[before:before+i])
    before = i
plyst_pca

[array([[ 1.21171386,  1.24261799, -2.72177722, ...,  0.35716371,
          1.89988589,  0.09115786],
        [-1.22587802,  0.29827552, -1.60352623, ...,  1.24213044,
          1.57743626,  1.59050851],
        [-0.10109538,  0.39034778,  2.3952013 , ..., -0.56470791,
         -0.48897189, -0.06998761],
        ...,
        [-0.9304078 ,  0.70921335, -0.80054393, ..., -1.06645616,
         -0.11984583, -0.27648739],
        [-0.48829761,  1.35948146,  0.95259216, ..., -0.69087526,
          1.1867872 ,  1.29889098],
        [-1.06400189,  0.99297621, -0.00562132, ..., -0.29502439,
         -0.23461115,  0.60336116]]),
 array([[ 0.15508233, -0.51784695, -0.04660487, ..., -0.97239895,
          0.38022487,  1.17688633],
        [ 0.23713279,  0.01997361,  0.76162261, ..., -1.15497181,
          0.1957792 ,  1.47608491],
        [ 0.44072959,  1.68720666, -0.98973789, ...,  0.46253032,
          0.90292783,  0.2848403 ],
        ...,
        [-0.37312612,  0.31299591,  0.17129647, ..., -

In [15]:
# import numpy as np
# plyst_pca = np.asarray(plyst_pca)
# print(plyst_pca.shape)
# print(type(plyst_pca))

mel 패딩

In [16]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

#display(plyst_pca)
plyst_pca= pad_sequences(plyst_pca, dtype='float32')
display(plyst_pca)
print(plyst_pca.shape)

array([[[ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        ...,
        [-0.9304078 ,  0.7092134 , -0.8005439 , ..., -1.0664562 ,
         -0.11984583, -0.27648738],
        [-0.4882976 ,  1.3594815 ,  0.95259213, ..., -0.69087523,
          1.1867872 ,  1.298891  ],
        [-1.0640019 ,  0.9929762 , -0.00562132, ..., -0.2950244 ,
         -0.23461115,  0.6033611 ]],

       [[ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        ...,
        [-0.37312612,  0.3129959 ,  0.17129648, ..., -

(100, 161, 100)


In [17]:
print(np.max(plyst_pca))
print(np.min(plyst_pca))

10.077227
-6.2048526


In [18]:
plyst_pca.shape

(100, 161, 100)

tag 임베딩

In [19]:
import pandas as pd
train_all= pd.read_json('data/train.json', encoding='utf-8', typ = 'frame')
#test= pd.read_json('test.json', encoding='utf-8', typ = 'frame')
train_all=train_all.sort_values(by='like_cnt', ascending=False)
#test = test.sort_values(by='like_cnt', ascending=False)
train=train_all[0:100]

In [20]:
from gensim.models.word2vec import Word2Vec

In [21]:
a_tags=train_all['tags']

In [22]:
eb_model = Word2Vec(a_tags,         # 리스트 형태의 데이터
                 sg=1,         # 0: CBOW, 1: Skip-gram
                 size=100,     # 벡터 크기
                 window=2,     # 고려할 앞뒤 폭(앞뒤 3단어)
                 min_count=0,  # 사용할 단어의 최소 빈도(0회 이하 단어 무시)
                 workers=4)    # 동시에 처리할 작업 수(코어 수와 비슷하게 설정)

# model.init_sims(replace=True) 필요없는 메모리 unload

In [23]:
eb_model.save('word2vec.model')

In [24]:
eb_model = Word2Vec.load('word2vec.model')

In [25]:
NUM_WORDS, EMB_DIM = eb_model.wv.vectors.shape

In [26]:
NUM_WORDS

29160

In [27]:
EMB_DIM

100

In [28]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [29]:
tags=train['tags']
tags=tags.tolist()

In [30]:
token = Tokenizer()
token.fit_on_texts(tags)
tags = token.texts_to_sequences(tags)
print(tags)

[[40, 20, 1, 6, 2, 25, 7, 10], [4, 11, 93, 18, 8, 57, 94, 12, 3, 10], [16, 5, 95, 13, 1, 17, 41, 2, 3], [58, 1, 6, 2, 59, 96, 60, 61, 97, 10], [12, 8, 2], [98, 29, 9, 99, 21, 26, 3], [5], [8, 9, 18, 11, 4, 26, 62, 42], [100, 22, 101, 43, 12, 44, 30], [4, 9, 102, 31, 11, 42, 103, 104, 32, 105], [63, 106, 107, 108, 109, 33, 64, 110, 111, 65], [8, 5, 45, 1, 21, 17, 112, 2, 7, 13], [14], [3], [8, 12, 46], [113, 43, 1, 6, 114, 2, 25], [4, 9, 14, 19, 1, 66, 30, 23], [12, 8, 9, 11], [3, 18, 16, 46, 24], [115], [67, 16, 116, 117, 118, 68, 41, 2, 69, 3], [119, 47], [27, 7], [7, 2], [70, 1, 59, 17, 120, 2, 34, 48, 3, 10], [14], [5, 49, 50, 6, 71, 72, 3, 24], [51, 73, 18, 62, 121, 122, 26, 32, 123], [74, 4, 16, 5, 15, 1, 17, 2, 57, 3], [26], [51, 52, 40, 73, 11, 31, 124, 35, 44, 32], [67, 36, 50, 19, 75, 66, 125, 126, 127, 23], [76], [128, 37, 27, 15, 129], [28, 130, 47, 20, 1, 2, 25, 10], [27, 15, 1, 53, 131, 2, 132, 7, 10], [70, 38, 50, 133, 35, 134, 34, 135, 77, 136], [39, 23, 15], [137, 138, 

In [31]:
tags= pad_sequences(tags)
#tags.shape
#type(tags)
tags

array([[  0,   0,  40,  20,   1,   6,   2,  25,   7,  10],
       [  4,  11,  93,  18,   8,  57,  94,  12,   3,  10],
       [  0,  16,   5,  95,  13,   1,  17,  41,   2,   3],
       [ 58,   1,   6,   2,  59,  96,  60,  61,  97,  10],
       [  0,   0,   0,   0,   0,   0,   0,  12,   8,   2],
       [  0,   0,   0,  98,  29,   9,  99,  21,  26,   3],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   5],
       [  0,   0,   8,   9,  18,  11,   4,  26,  62,  42],
       [  0,   0,   0, 100,  22, 101,  43,  12,  44,  30],
       [  4,   9, 102,  31,  11,  42, 103, 104,  32, 105],
       [ 63, 106, 107, 108, 109,  33,  64, 110, 111,  65],
       [  8,   5,  45,   1,  21,  17, 112,   2,   7,  13],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,  14],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   3],
       [  0,   0,   0,   0,   0,   0,   0,   8,  12,  46],
       [  0,   0,   0, 113,  43,   1,   6, 114,   2,  25],
       [  0,   0,   4,   9,  14,  19,   1,  66,  30,  23

In [32]:
print(tags.shape)

(100, 10)


# MODEL

In [33]:
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Embedding,Input,LSTM,Dense,Activation
from tensorflow.keras.layers import add

In [34]:
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Embedding,Input,LSTM,Dense,Activation,Concatenate,Reshape, Lambda
from tensorflow.keras.layers import add, Reshape
from tensorflow.keras.optimizers import SGD, RMSprop, Adam
from tensorflow.keras.backend import expand_dims
from tensorflow.keras.layers import LeakyReLU


def slice_tensor1(input):
    return input[:,0:10,:]

def slice_tensor2(input):
    return input[:,10:171,:]


##########################################

# Input 1: tags (5,10)
tag_input_a = Input(shape =(10,),name = 'tag_input')

# Input 1: Embedding layer
tag_input_b = Embedding(input_dim=NUM_WORDS, output_dim=EMB_DIM,trainable=False, input_length = 10,weights=[eb_model.wv.vectors])(tag_input_a)

##########################################

# Input 2: mel_spectrogram (5,200,100)
mel_input_a = Input(shape=(161,100), name='mel_input')

##########################################

# Concatenation layer here
x = Concatenate(axis = 1)([tag_input_b, mel_input_a])
x2 = Dense(100, activation='relu')(x)
x3 = Dense(100, activation='relu', name = "journey_embeddings")(x2)

#output = Activation("softmax")(x3)

##########################################

out1 = Lambda(slice_tensor1)(x3)
out2 = Lambda(slice_tensor2)(x3)

output1 = Dense(1, activation='relu', name='tags')(out1)
print(output1)

output2 = Dense(100, activation='relu', name='plyst_pca')(out2)
print(output2)

# output1 = Dense(1, activation=LeakyReLU(alpha = 0.1))(out1)
# output2 = Dense(100, activation=LeakyReLU(alpha = 0.1))(out2)
    
'''# An abitrary number of dense, hidden layers here
xt1 = Dense(20, activation='relu')(x3)
xt2 = Dense(10, activation='relu')(xt1)


xm = Dense(100, activation='relu')(x3)
xm2 = Reshape((210, 100))(xm)'''

#print(model.summary())
##########################################
adam = Adam(lr=0.001)
## Compile and fit the model
model = Model(inputs=[tag_input_a, mel_input_a], outputs=[output1, output2])
model.compile(loss = {'tags':'mse', 'plyst_pca':'mse'},optimizer = 'adam', metrics={'tags':'accuracy', 'plyst_pca':'accuracy'})
print(model.summary())
# np.random.seed(21)

Tensor("tags/Identity:0", shape=(None, 10, 1), dtype=float32)
Tensor("plyst_pca/Identity:0", shape=(None, 161, 100), dtype=float32)
Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
tag_input (InputLayer)          [(None, 10)]         0                                            
__________________________________________________________________________________________________
embedding (Embedding)           (None, 10, 100)      2916000     tag_input[0][0]                  
__________________________________________________________________________________________________
mel_input (InputLayer)          [(None, 161, 100)]   0                                            
__________________________________________________________________________________________________
concatenate (Concatenate)       (None, 171, 100)     0       

In [35]:
model.fit([tags, plyst_pca], [tags, plyst_pca], batch_size=1, validation_split=0.2, epochs=50)

Train on 80 samples, validate on 20 samples
Epoch 1/50
80/80 [==============================] - 3s 34ms/sample - loss: 4026.6005 - tags_loss: 4025.9753 - plyst_pca_loss: 0.6251 - tags_accuracy: 0.0487 - plyst_pca_accuracy: 0.3160 - val_loss: 8968.7810 - val_tags_loss: 8968.2900 - val_plyst_pca_loss: 0.4908 - val_tags_accuracy: 0.0150 - val_plyst_pca_accuracy: 0.5360
Epoch 2/50
80/80 [==============================] - 1s 14ms/sample - loss: 3063.7558 - tags_loss: 3063.1792 - plyst_pca_loss: 0.5768 - tags_accuracy: 0.0312 - plyst_pca_accuracy: 0.1408 - val_loss: 8093.6951 - val_tags_loss: 8093.2295 - val_plyst_pca_loss: 0.4656 - val_tags_accuracy: 0.0150 - val_plyst_pca_accuracy: 0.0814
Epoch 3/50
80/80 [==============================] - 1s 14ms/sample - loss: 2427.3962 - tags_loss: 2426.8450 - plyst_pca_loss: 0.5513 - tags_accuracy: 0.0312 - plyst_pca_accuracy: 0.1153 - val_loss: 6486.1837 - val_tags_loss: 6485.7354 - val_plyst_pca_loss: 0.4489 - val_tags_accuracy: 0.0150 - val_plyst_pc

In [36]:
#Test Set Evaluation.
y_pred = model.predict([tags, plyst_pca], batch_size=1)

[array([[[0.00000000e+00],
        [0.00000000e+00],
        [6.79202194e+01],
        [4.02532482e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [1.29453917e+01],
        [0.00000000e+00],
        [0.00000000e+00]],

       [[0.00000000e+00],
        [0.00000000e+00],
        [7.99860229e+01],
        [9.00322628e+00],
        [0.00000000e+00],
        [3.35151520e+01],
        [8.32690582e+01],
        [1.23003274e-02],
        [0.00000000e+00],
        [0.00000000e+00]],

       [[0.00000000e+00],
        [8.07710361e+00],
        [0.00000000e+00],
        [1.23663567e+02],
        [1.13450460e+01],
        [0.00000000e+00],
        [2.26911974e+00],
        [3.50209236e+01],
        [0.00000000e+00],
        [0.00000000e+00]],

       [[5.21800499e+01],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [4.57720451e+01],
        [1.13509163e+02],
        [5.89386063e+01],
        [5.89610481e+01],
     

In [44]:
# print(y_pred)
print(len(y_pred))
print(y_pred[0].shape)
print(y_pred[1].shape)

2
(100, 10, 1)
(100, 161, 100)


In [45]:
tags.shape

(100, 10)

In [46]:
plyst_pca.shape

(100, 161, 100)

In [49]:
#1st plyst_tag  y_pred
print(y_pred[0][0])

[[ 0.      ]
 [ 0.      ]
 [67.92022 ]
 [ 4.025325]
 [ 0.      ]
 [ 0.      ]
 [ 0.      ]
 [12.945392]
 [ 0.      ]
 [ 0.      ]]


In [53]:
print(tags[0])

[ 0  0 40 20  1  6  2 25  7 10]


In [52]:
#1st plyst_mel  y_pred
print(y_pred[1][0])

[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.18270105 0.        ]
 [0.         0.         0.         ... 0.         0.8281016  0.9538273 ]
 [0.         0.         0.         ... 0.         0.         0.39031446]]


In [54]:
print(plyst_pca[0])

[[ 0.          0.          0.         ...  0.          0.
   0.        ]
 [ 0.          0.          0.         ...  0.          0.
   0.        ]
 [ 0.          0.          0.         ...  0.          0.
   0.        ]
 ...
 [-0.9304078   0.7092134  -0.8005439  ... -1.0664562  -0.11984583
  -0.27648738]
 [-0.4882976   1.3594815   0.95259213 ... -0.69087523  1.1867872
   1.298891  ]
 [-1.0640019   0.9929762  -0.00562132 ... -0.2950244  -0.23461115
   0.6033611 ]]
