In [1]:
import pandas as pd
import pickle
with open('result.txt','rb') as f:
    result=pickle.load(f)
# for i in range(6):
#     i= i+1
#     with open('result/'+'result'+str(i)+'.txt','rb') as f:
#          globals()['result%s' % str(i)] = pickle.load(f) #pickle 불러오기
# result1

In [2]:
# result = pd.concat([result1,result2,result3,result4,result5,result6])

In [3]:
result

plyst_id  track_id                                                mel
0       74220    438327  [1.2117138606529596, 1.2426179863603755, -2.72...
1       74220    434095  [-1.2258780182684197, 0.29827552237975175, -1....
2       74220    443160  [-0.1010953804385185, 0.39034777978670515, 2.3...
3       74220    674508  [0.6204721094550578, -0.2093501876515369, -0.1...
4       74220    695548  [0.5324769186996661, -0.037027993332340324, -0...
..        ...       ...                                                ...
793     45283    555322  [-0.43457666700875563, -1.6963845491780836, -0...
794     45283    550374  [-0.45193886322138593, -0.633085508702738, 0.4...
795     45283    555344  [-0.13414141019638112, 1.3242597210568723, 0.0...
796    102037    553846  [-0.17395788994908945, -0.32571804039205765, 0...
797    102037    553430  [-0.9071539670970147, -0.06288896585829448, -0...

[9873 rows x 3 columns]

In [4]:
mel=result['mel']
mel=mel.to_list()
#type(mel)

In [5]:
import numpy as np
mel_a = np.array(mel)

In [6]:
mel_a

array([[ 1.21171386,  1.24261799, -2.72177722, ...,  0.35716371,
         1.89988589,  0.09115786],
       [-1.22587802,  0.29827552, -1.60352623, ...,  1.24213044,
         1.57743626,  1.59050851],
       [-0.10109538,  0.39034778,  2.3952013 , ..., -0.56470791,
        -0.48897189, -0.06998761],
       ...,
       [-0.13414141,  1.32425972,  0.04912668, ...,  0.26048188,
        -0.53928892, -0.3316256 ],
       [-0.17395789, -0.32571804,  0.02596743, ...,  0.83150753,
        -0.69656022,  0.37871913],
       [-0.90715397, -0.06288897, -0.81939989, ...,  1.34319165,
        -2.09927769, -0.37695129]])

In [7]:
plyst_id=result['plyst_id']
plyst_id=plyst_id.to_list()

In [8]:
count={}
for i in plyst_id:
    try:count[i]+=1
    except:count[i]=1
print(count)

{74220: 81, 122388: 155, 26174: 156, 72658: 50, 113501: 115, 72684: 155, 38507: 42, 39508: 147, 102123: 148, 11762: 77, 20981: 141, 20007: 51, 12363: 140, 56212: 58, 16202: 62, 46950: 40, 102414: 93, 8869: 157, 49159: 129, 16689: 150, 55982: 160, 149070: 45, 21128: 64, 142071: 91, 143708: 123, 107845: 104, 15740: 156, 46039: 59, 45601: 65, 87546: 54, 59787: 39, 124868: 149, 138343: 144, 43355: 104, 35856: 75, 60139: 161, 98049: 40, 26898: 135, 20163: 136, 37684: 30, 18845: 147, 27857: 44, 152256: 84, 86321: 146, 82009: 94, 14719: 138, 88785: 42, 70158: 60, 27826: 62, 17936: 156, 142136: 70, 110685: 44, 77356: 148, 17822: 96, 70136: 145, 115584: 152, 141531: 136, 94043: 145, 113076: 46, 73726: 151, 141475: 60, 91291: 136, 52637: 76, 114425: 140, 23771: 148, 108324: 47, 54629: 132, 139249: 37, 911: 41, 49256: 37, 125424: 82, 72069: 143, 119200: 151, 86457: 60, 43328: 132, 139546: 138, 80518: 145, 46724: 143, 97906: 73, 61165: 67, 13315: 138, 56663: 147, 145841: 129, 101299: 129, 47207: 1

In [9]:
long=list(count.values())
len(long)

100

In [10]:
'''#for i in 
songs=train['songs']
type(songs)
songs = pd.DataFrame(songs)
long=[]
for i, row in songs.iterrows():
    for a in row:
        long.append(len(a))
#long'''

"#for i in \nsongs=train['songs']\ntype(songs)\nsongs = pd.DataFrame(songs)\nlong=[]\nfor i, row in songs.iterrows():\n    for a in row:\n        long.append(len(a))\n#long"

In [11]:
plyst_pca =[]
before = 0
for i in long:
    plyst_pca.append(mel_a[before:before+i])
    before = i
plyst_pca

[array([[ 1.21171386,  1.24261799, -2.72177722, ...,  0.35716371,
          1.89988589,  0.09115786],
        [-1.22587802,  0.29827552, -1.60352623, ...,  1.24213044,
          1.57743626,  1.59050851],
        [-0.10109538,  0.39034778,  2.3952013 , ..., -0.56470791,
         -0.48897189, -0.06998761],
        ...,
        [-0.9304078 ,  0.70921335, -0.80054393, ..., -1.06645616,
         -0.11984583, -0.27648739],
        [-0.48829761,  1.35948146,  0.95259216, ..., -0.69087526,
          1.1867872 ,  1.29889098],
        [-1.06400189,  0.99297621, -0.00562132, ..., -0.29502439,
         -0.23461115,  0.60336116]]),
 array([[ 0.15508233, -0.51784695, -0.04660487, ..., -0.97239895,
          0.38022487,  1.17688633],
        [ 0.23713279,  0.01997361,  0.76162261, ..., -1.15497181,
          0.1957792 ,  1.47608491],
        [ 0.44072959,  1.68720666, -0.98973789, ...,  0.46253032,
          0.90292783,  0.2848403 ],
        ...,
        [-0.37312612,  0.31299591,  0.17129647, ..., -

In [12]:
# plyst_pca=np.array(plyst_pca)

In [13]:
plyst_pca=np.array(plyst_pca)
plyst_pca.shape

(100,)

In [14]:
plyst_pca[0].shape

(81, 100)

In [15]:
# import numpy as np
# plyst_pca = np.asarray(plyst_pca)
# print(plyst_pca.shape)
# print(type(plyst_pca))

In [16]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

#display(plyst_pca)
plyst_pca= pad_sequences(plyst_pca, dtype='float32')
display(plyst_pca)
print(plyst_pca.shape)

array([[[ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        ...,
        [-0.9304078 ,  0.7092134 , -0.8005439 , ..., -1.0664562 ,
         -0.11984583, -0.27648738],
        [-0.4882976 ,  1.3594815 ,  0.95259213, ..., -0.69087523,
          1.1867872 ,  1.298891  ],
        [-1.0640019 ,  0.9929762 , -0.00562132, ..., -0.2950244 ,
         -0.23461115,  0.6033611 ]],

       [[ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        ...,
        [-0.37312612,  0.3129959 ,  0.17129648, ..., -

(100, 161, 100)


In [17]:
print(np.max(plyst_pca))
print(np.min(plyst_pca))

10.077227
-6.2048526


In [18]:
plyst_pca.shape

(100, 161, 100)

tag 임베딩

In [20]:
import pandas as pd
train_all= pd.read_json('train.json', encoding='utf-8', typ = 'frame')
#test= pd.read_json('test.json', encoding='utf-8', typ = 'frame')
train_all=train_all.sort_values(by='like_cnt', ascending=False)
#test = test.sort_values(by='like_cnt', ascending=False)
train=train_all[0:100]

In [21]:
from gensim.models.word2vec import Word2Vec

In [22]:
a_tags=train_all['tags']

In [23]:
eb_model = Word2Vec(a_tags,         # 리스트 형태의 데이터
                 sg=1,         # 0: CBOW, 1: Skip-gram
                 size=100,     # 벡터 크기
                 window=2,     # 고려할 앞뒤 폭(앞뒤 3단어)
                 min_count=0,  # 사용할 단어의 최소 빈도(0회 이하 단어 무시)
                 workers=4)    # 동시에 처리할 작업 수(코어 수와 비슷하게 설정)

# model.init_sims(replace=True) 필요없는 메모리 unload

In [24]:
eb_model.save('word2vec.model')

In [25]:
eb_model = Word2Vec.load('word2vec.model')

In [26]:
NUM_WORDS, EMB_DIM = eb_model.wv.vectors.shape

In [27]:
NUM_WORDS

29160

In [28]:
EMB_DIM

100

In [29]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [30]:
tags=train['tags']
tags=tags.tolist()

In [31]:
token = Tokenizer()
token.fit_on_texts(tags)
tags = token.texts_to_sequences(tags)
print(tags)

[[40, 20, 1, 6, 2, 25, 7, 10], [4, 11, 93, 18, 8, 57, 94, 12, 3, 10], [16, 5, 95, 13, 1, 17, 41, 2, 3], [58, 1, 6, 2, 59, 96, 60, 61, 97, 10], [12, 8, 2], [98, 29, 9, 99, 21, 26, 3], [5], [8, 9, 18, 11, 4, 26, 62, 42], [100, 22, 101, 43, 12, 44, 30], [4, 9, 102, 31, 11, 42, 103, 104, 32, 105], [63, 106, 107, 108, 109, 33, 64, 110, 111, 65], [8, 5, 45, 1, 21, 17, 112, 2, 7, 13], [14], [3], [8, 12, 46], [113, 43, 1, 6, 114, 2, 25], [4, 9, 14, 19, 1, 66, 30, 23], [12, 8, 9, 11], [3, 18, 16, 46, 24], [115], [67, 16, 116, 117, 118, 68, 41, 2, 69, 3], [119, 47], [27, 7], [7, 2], [70, 1, 59, 17, 120, 2, 34, 48, 3, 10], [14], [5, 49, 50, 6, 71, 72, 3, 24], [51, 73, 18, 62, 121, 122, 26, 32, 123], [74, 4, 16, 5, 15, 1, 17, 2, 57, 3], [26], [51, 52, 40, 73, 11, 31, 124, 35, 44, 32], [67, 36, 50, 19, 75, 66, 125, 126, 127, 23], [76], [128, 37, 27, 15, 129], [28, 130, 47, 20, 1, 2, 25, 10], [27, 15, 1, 53, 131, 2, 132, 7, 10], [70, 38, 50, 133, 35, 134, 34, 135, 77, 136], [39, 23, 15], [137, 138, 

In [32]:
tags= pad_sequences(tags)
#tags.shape
#type(tags)
tags

array([[  0,   0,  40,  20,   1,   6,   2,  25,   7,  10],
       [  4,  11,  93,  18,   8,  57,  94,  12,   3,  10],
       [  0,  16,   5,  95,  13,   1,  17,  41,   2,   3],
       [ 58,   1,   6,   2,  59,  96,  60,  61,  97,  10],
       [  0,   0,   0,   0,   0,   0,   0,  12,   8,   2],
       [  0,   0,   0,  98,  29,   9,  99,  21,  26,   3],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   5],
       [  0,   0,   8,   9,  18,  11,   4,  26,  62,  42],
       [  0,   0,   0, 100,  22, 101,  43,  12,  44,  30],
       [  4,   9, 102,  31,  11,  42, 103, 104,  32, 105],
       [ 63, 106, 107, 108, 109,  33,  64, 110, 111,  65],
       [  8,   5,  45,   1,  21,  17, 112,   2,   7,  13],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,  14],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   3],
       [  0,   0,   0,   0,   0,   0,   0,   8,  12,  46],
       [  0,   0,   0, 113,  43,   1,   6, 114,   2,  25],
       [  0,   0,   4,   9,  14,  19,   1,  66,  30,  23

In [33]:
print(tags.shape)

(100, 10)


In [34]:
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Embedding,Input,LSTM,Dense,Activation
from tensorflow.keras.layers import add

In [35]:
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Embedding,Input,LSTM,Dense,Activation,Concatenate,Reshape, Lambda
from tensorflow.keras.layers import add, Reshape
from tensorflow.keras.optimizers import SGD, RMSprop, Adam
from tensorflow.keras.backend import expand_dims
from tensorflow.keras.layers import LeakyReLU


def slice_tensor1(input):
    return input[:,0:10,:]

def slice_tensor2(input):
    return input[:,10:171,:]


##########################################

# Input 1: tags (5,10)
tag_input_a = Input(shape =(10,),name = 'tag_input')

# Input 1: Embedding layer
tag_input_b = Embedding(input_dim=NUM_WORDS, output_dim=EMB_DIM,trainable=False, input_length = 10,weights=[eb_model.wv.vectors])(tag_input_a)

##########################################

# Input 2: mel_spectrogram (5,200,100)
mel_input_a = Input(shape=(161,100), name='mel_input')

##########################################

# Concatenation layer here
x = Concatenate(axis = 1)([tag_input_b, mel_input_a])
x2 = Dense(100, activation='relu')(x)
x3 = Dense(100, activation='relu', name = "journey_embeddings")(x2)

#output = Activation("softmax")(x3)

##########################################

out1 = Lambda(slice_tensor1)(x3)
out2 = Lambda(slice_tensor2)(x3)

output1 = Dense(1, activation='relu', name='tags')(out1)
print(output1)

output2 = Dense(100, activation='relu', name='plyst_pca')(out2)
print(output2)

# output1 = Dense(1, activation=LeakyReLU(alpha = 0.1))(out1)
# output2 = Dense(100, activation=LeakyReLU(alpha = 0.1))(out2)
    
'''# An abitrary number of dense, hidden layers here
xt1 = Dense(20, activation='relu')(x3)
xt2 = Dense(10, activation='relu')(xt1)


xm = Dense(100, activation='relu')(x3)
xm2 = Reshape((210, 100))(xm)'''

#print(model.summary())
##########################################
adam = Adam(lr=0.001)
## Compile and fit the model
model = Model(inputs=[tag_input_a, mel_input_a], outputs=[output1, output2])
model.compile(loss = {'tags':'mse', 'plyst_pca':'mse'},optimizer = 'adam', metrics={'tags':'accuracy', 'plyst_pca':'accuracy'})
print(model.summary())
# np.random.seed(21)

Tensor("tags/Identity:0", shape=(None, 10, 1), dtype=float32)
Tensor("plyst_pca/Identity:0", shape=(None, 161, 100), dtype=float32)
Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
tag_input (InputLayer)          [(None, 10)]         0                                            
__________________________________________________________________________________________________
embedding (Embedding)           (None, 10, 100)      2916000     tag_input[0][0]                  
__________________________________________________________________________________________________
mel_input (InputLayer)          [(None, 161, 100)]   0                                            
__________________________________________________________________________________________________
concatenate (Concatenate)       (None, 171, 100)     0       

In [68]:
print(out1)

Tensor("lambda/Identity:0", shape=(None, 10, 100), dtype=float32)


In [ ]:
output2

In [36]:
model.fit([tags, plyst_pca], [tags, plyst_pca], batch_size=1, validation_split=0.2, epochs=50)

Epoch 1/50
80/80 [==============================] - 0s 5ms/step - loss: 3854.3972 - tags_loss: 3853.7720 - plyst_pca_loss: 0.6254 - tags_accuracy: 0.0437 - plyst_pca_accuracy: 0.2697 - val_loss: 8779.4395 - val_tags_loss: 8778.9502 - val_plyst_pca_loss: 0.4897 - val_tags_accuracy: 0.0150 - val_plyst_pca_accuracy: 0.0565
Epoch 2/50
80/80 [==============================] - 0s 3ms/step - loss: 2900.7288 - tags_loss: 2900.1550 - plyst_pca_loss: 0.5745 - tags_accuracy: 0.0312 - plyst_pca_accuracy: 0.1090 - val_loss: 7145.2280 - val_tags_loss: 7144.7686 - val_plyst_pca_loss: 0.4603 - val_tags_accuracy: 0.0150 - val_plyst_pca_accuracy: 0.0944
Epoch 3/50
80/80 [==============================] - 0s 3ms/step - loss: 2394.6753 - tags_loss: 2394.1294 - plyst_pca_loss: 0.5454 - tags_accuracy: 0.0500 - plyst_pca_accuracy: 0.1408 - val_loss: 6678.6680 - val_tags_loss: 6678.2266 - val_plyst_pca_loss: 0.4415 - val_tags_accuracy: 0.4150 - val_plyst_pca_accuracy: 0.1248
Epoch 4/50
80/80 [================

In [37]:
#Test Set Evaluation.
y_pred = model.predict([tags, plyst_pca], batch_size=1)

In [38]:
# print(y_pred)
print(len(y_pred))
print(y_pred[0].shape)
print(y_pred[1].shape)

2
(100, 10, 1)
(100, 161, 100)


In [39]:
tags.shape

(100, 10)

In [40]:
plyst_pca.shape

(100, 161, 100)

# 코사인 유사도 확인

In [45]:
#tag 유사도
from numpy import dot
from numpy.linalg import norm
import numpy as np
def cos_sim(A, B):
       return dot(A, B)/(norm(A)*norm(B))

In [47]:
#1st plyst_tag  y_pred
a=y_pred[0][0]

In [50]:

a=np.array(a).T
a

array([[ 0.      ,  0.      , 56.52408 , 33.472282,  6.127239,  0.      ,
         0.      , 34.170692, 12.763468,  0.      ]], dtype=float32)

In [48]:
b=tags[0]

In [51]:
print(cos_sim(a, b))

[0.97006983]


In [ ]:
#mel_spectrogram 유사도
from sklearn.metrics.pairwise import cosine_similarity

In [59]:
#1st plyst_mel  y_pred
A=y_pred[1][0] #예측된 mel 

In [61]:
B=plyst_pca[0] #실제 mel

In [60]:
#2차원 배열 flatten
A_flat=np.ravel(A, order='C')
A_flat

array([0.        , 0.04400805, 0.        , ..., 0.        , 0.        ,
       0.16646652], dtype=float32)

In [62]:
B_flat=np.ravel(B, order='C')
B_flat

array([ 0.        ,  0.        ,  0.        , ..., -0.2950244 ,
       -0.23461115,  0.6033611 ], dtype=float32)

In [64]:
print(cos_sim(A_flat, B_flat))

0.44970444
